# Generated by Django 5.2.14 on 2026-05-21 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("PASSENGER", "Course passager"),
                            ("DELIVERY", "Livraison"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("MOTO_2W", "Moto 2 roues"),
                            ("MOTO_3W", "Moto 3 roues"),
                        ],
                        max_length=10,
                    ),
                ),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_per_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("minimum_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "night_surcharge_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("night_start_hour", models.PositiveSmallIntegerField(default=22)),
                ("night_end_hour", models.PositiveSmallIntegerField(default=5)),
                ("delivery_size_surcharge", models.JSONField(default=dict)),
                (
                    "delivery_urgency_surcharge_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pricing_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle tarifaire",
                "verbose_name_plural": "Règles tarifaires",
                "db_table": "sira_pricing_rule",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("service_type", "vehicle_type"),
                        name="unique_active_pricing_per_service_vehicle",
                    )
                ],
            },
        ),
    ]
