# Generated by Django 5.2.14 on 2026-05-21 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("TERMS_PLATFORM", "CGU Plateforme"),
                            ("TERMS_DRIVER", "CGU Conducteur"),
                            ("TERMS_CLIENT", "CGU Client"),
                            ("PRIVACY_POLICY", "Politique de confidentialité"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("effective_from", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_legal_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document légal",
                "verbose_name_plural": "Documents légaux",
                "db_table": "sira_legal_document",
            },
        ),
        migrations.CreateModel(
            name="UserAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                (
                    "acceptance_method",
                    models.CharField(
                        choices=[
                            ("CHECKBOX", "Case à cocher"),
                            ("CHECKBOX_TYPED", "Case + phrase saisie"),
                            ("SIGNATURE", "Signature"),
                        ],
                        default="CHECKBOX",
                        max_length=20,
                    ),
                ),
                ("typed_confirmation", models.CharField(blank=True, max_length=200)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="legal.legaldocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Acceptation CGU",
                "verbose_name_plural": "Acceptations CGU",
                "db_table": "sira_user_acceptance",
            },
        ),
        migrations.AddConstraint(
            model_name="legaldocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("document_type",),
                name="unique_active_document_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="legaldocument",
            constraint=models.UniqueConstraint(
                fields=("document_type", "version"),
                name="unique_version_per_document_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="useracceptance",
            constraint=models.UniqueConstraint(
                fields=("user", "document"), name="unique_acceptance_per_user_document"
            ),
        ),
    ]
