# Generated by Django 5.2.14 on 2026-05-22 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSanction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sanction_type",
                    models.CharField(
                        choices=[
                            ("WARNING", "Avertissement"),
                            ("TEMP_SUSPEND", "Suspension temporaire"),
                            ("PERMANENT_BAN", "Bannissement définitif"),
                            ("FIN_PENALTY", "Pénalité financière"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "penalty_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_appealed", models.BooleanField(default=False)),
                ("appeal_text", models.TextField(blank=True)),
                ("appeal_resolution", models.TextField(blank=True)),
                ("appeal_resolved_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sanctions_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_ride",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanctions",
                        to="rides.ride",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sanctions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sanction",
                "verbose_name_plural": "Sanctions",
                "db_table": "sira_user_sanction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="sira_user_s_user_id_c399f1_idx"
                    ),
                    models.Index(
                        fields=["sanction_type"], name="sira_user_s_sanctio_068c6f_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="sira_user_s_is_acti_626f7d_idx"
                    ),
                ],
            },
        ),
    ]
