# Generated by Django 5.2.14 on 2026-05-22 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
        ("safety", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sosalert",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Alerte SOS",
                "verbose_name_plural": "Alertes SOS",
            },
        ),
        migrations.AddField(
            model_name="sosalert",
            name="emergency_contact_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sosalert",
            name="resolution_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sosalert",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="sosalert",
            index=models.Index(fields=["status"], name="sira_sos_al_status_29d9d0_idx"),
        ),
        migrations.AddIndex(
            model_name="sosalert",
            index=models.Index(fields=["user"], name="sira_sos_al_user_id_c891e7_idx"),
        ),
        migrations.AlterModelTable(
            name="sosalert",
            table="sira_sos_alert",
        ),
    ]
