# Generated by Django 5.2.14 on 2026-05-21 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverPayout",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("rides_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échoué"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("operator_response", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("initiated_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="drivers.driverprofile",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reversement conducteur",
                "verbose_name_plural": "Reversements conducteurs",
                "db_table": "sira_driver_payout",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("ORANGE", "Orange Money"),
                            ("MOOV", "Moov Money"),
                            ("CASH", "Espèces"),
                            ("WALLET", "Wallet Sira"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échoué"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("operator_response", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("webhook_received_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_signature_valid", models.BooleanField(default=False)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("breakdown", models.JSONField(default=dict)),
                (
                    "ride",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "db_table": "sira_payment",
                "indexes": [
                    models.Index(
                        fields=["status"], name="sira_paymen_status_4b29cd_idx"
                    ),
                    models.Index(
                        fields=["operator"], name="sira_paymen_operato_341d81_idx"
                    ),
                ],
            },
        ),
    ]
