# Generated by Django 5.2.14 on 2026-05-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchingConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "weight_distance",
                    models.DecimalField(decimal_places=3, default=0.55, max_digits=4),
                ),
                (
                    "weight_quality",
                    models.DecimalField(decimal_places=3, default=0.3, max_digits=4),
                ),
                (
                    "weight_waiting_time",
                    models.DecimalField(decimal_places=3, default=0.15, max_digits=4),
                ),
                (
                    "score_threshold_warning",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "score_threshold_suspension",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
                ),
                ("max_search_radius_m", models.PositiveIntegerField(default=5000)),
                ("initial_search_radius_m", models.PositiveIntegerField(default=1000)),
                ("dispatch_batch_size", models.PositiveSmallIntegerField(default=3)),
                (
                    "driver_response_timeout_s",
                    models.PositiveSmallIntegerField(default=15),
                ),
                (
                    "total_dispatch_timeout_s",
                    models.PositiveSmallIntegerField(default=90),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Configuration matching",
                "verbose_name_plural": "Configurations matching",
                "db_table": "sira_matching_config",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="unique_active_matching_config",
                    )
                ],
            },
        ),
    ]
