# Generated by Django 5.2.14 on 2026-05-20 11:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=50)),
                ("permissions_scope", models.JSONField(default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "ADMIN"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil administrateur",
                "verbose_name_plural": "Profils administrateurs",
                "db_table": "sira_admin_profile",
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="clients/photos/"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "preferred_payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ORANGE", "Orange Money"),
                            ("MOOV", "Moov Money"),
                            ("CASH", "Espèces"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_pickup_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("total_rides", models.PositiveIntegerField(default=0)),
                (
                    "client_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "CLIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil client",
                "verbose_name_plural": "Profils clients",
                "db_table": "sira_client_profile",
            },
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="drivers/photos/")),
                ("mobile_money_number", models.CharField(max_length=20)),
                (
                    "mobile_money_operator",
                    models.CharField(
                        choices=[("ORANGE", "Orange Money"), ("MOOV", "Moov Money")],
                        max_length=10,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                            ("SUSPENDED", "Suspendu"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=False)),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, db_index=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                (
                    "current_score",
                    models.DecimalField(
                        db_index=True, decimal_places=2, default=70.0, max_digits=5
                    ),
                ),
                ("last_score_update", models.DateTimeField(blank=True, null=True)),
                ("is_in_matching_suspension", models.BooleanField(default=False)),
                ("last_ride_completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_rides", models.PositiveIntegerField(default=0)),
                ("total_completed_rides", models.PositiveIntegerField(default=0)),
                ("total_cancelled_rides", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                (
                    "preferred_direction",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "preferred_direction_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "DRIVER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_drivers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil conducteur",
                "verbose_name_plural": "Profils conducteurs",
                "db_table": "sira_driver_profile",
            },
        ),
        migrations.CreateModel(
            name="DriverScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
                ),
                (
                    "rating_score",
                    models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
                ),
                (
                    "acceptance_score",
                    models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
                ),
                (
                    "completion_score",
                    models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
                ),
                (
                    "seniority_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "incident_score",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("computation_period_start", models.DateField()),
                ("computation_period_end", models.DateField()),
                ("rides_evaluated_count", models.PositiveIntegerField(default=0)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_history",
                        to="drivers.driverprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score conducteur",
                "verbose_name_plural": "Scores conducteurs",
                "db_table": "sira_driver_score",
                "ordering": ["-computed_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("MOTO_2W", "Moto 2 roues"),
                            ("MOTO_3W", "Moto 3 roues (tricycle)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=30)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("passenger_capacity", models.PositiveSmallIntegerField(default=1)),
                (
                    "cargo_capacity",
                    models.CharField(
                        choices=[
                            ("SMALL", "Petit"),
                            ("MEDIUM", "Moyen"),
                            ("LARGE", "Grand"),
                        ],
                        default="SMALL",
                        max_length=10,
                    ),
                ),
                ("required_license_type", models.CharField(default="A", max_length=2)),
                ("photo", models.ImageField(upload_to="vehicles/photos/")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="drivers.driverprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Véhicule",
                "verbose_name_plural": "Véhicules",
                "db_table": "sira_vehicle",
            },
        ),
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID_CARD", "Carte Nationale d'Identité"),
                            ("DRIVER_LICENSE", "Permis de conduire"),
                            ("VEHICLE_REGISTRATION", "Carte grise"),
                            ("INSURANCE", "Assurance"),
                            ("DRIVER_PHOTO", "Photo conducteur"),
                        ],
                        max_length=25,
                    ),
                ),
                ("file", models.ImageField(upload_to="drivers/documents/")),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                            ("EXPIRED", "Expiré"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="drivers.driverprofile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="drivers.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document conducteur",
                "verbose_name_plural": "Documents conducteurs",
                "db_table": "sira_driver_document",
            },
        ),
    ]
