# Generated by Django 5.2.14 on 2026-05-21 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=500)),
                ("is_flagged", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "rated",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
                "db_table": "sira_rating",
                "indexes": [
                    models.Index(
                        fields=["rated"], name="sira_rating_rated_i_3c7d62_idx"
                    ),
                    models.Index(
                        fields=["ride"], name="sira_rating_ride_id_1046fc_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ride", "rater"), name="unique_rating_per_ride_rater"
                    )
                ],
            },
        ),
    ]
