# Generated by Django 5.2.14 on 2026-05-21 12:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("PASSENGER", "Course passager"),
                            ("DELIVERY", "Livraison"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Demandée"),
                            ("ACCEPTED", "Acceptée"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "selection_method",
                    models.CharField(
                        choices=[
                            ("AUTO_DISPATCH", "Dispatch automatique"),
                            ("MANUAL_SELECTION", "Sélection manuelle"),
                        ],
                        default="AUTO_DISPATCH",
                        max_length=20,
                    ),
                ),
                (
                    "pickup_location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("pickup_address", models.CharField(blank=True, max_length=255)),
                (
                    "dropoff_location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("dropoff_address", models.CharField(blank=True, max_length=255)),
                (
                    "confirmed_dropoff_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "actual_route",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("estimated_distance_m", models.PositiveIntegerField()),
                (
                    "theoretical_distance_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "actual_distance_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pricing_snapshot", models.JSONField(default=dict)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                ("recipient_name", models.CharField(blank=True, max_length=100)),
                ("package_description", models.TextField(blank=True)),
                (
                    "package_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SMALL", "Petit"),
                            ("MEDIUM", "Moyen"),
                            ("LARGE", "Grand"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "package_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("package_is_fragile", models.BooleanField(default=False)),
                (
                    "package_value_fcfa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "package_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="rides/packages/"
                    ),
                ),
                ("is_urgent", models.BooleanField(default=False)),
                ("forbidden_content_certified", models.BooleanField(default=False)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("driver_arrived_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("fraud_flags", models.JSONField(default=list)),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "fraud_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("synced_from_offline", models.BooleanField(default=False)),
                ("client_local_id", models.CharField(blank=True, max_length=100)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides",
                        to="drivers.clientprofile",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rides",
                        to="drivers.driverprofile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rides",
                        to="drivers.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "sira_ride",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="RecipientPositionShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("recipient_phone", models.CharField(max_length=20)),
                (
                    "shared_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("shared_at", models.DateTimeField(blank=True, null=True)),
                ("shared_from_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("shared_from_user_agent", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SHARED", "Position partagée"),
                            ("EXPIRED", "Expiré"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("sms_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sms_provider_message_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "ride",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_share",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partage position destinataire",
                "verbose_name_plural": "Partages position destinataire",
                "db_table": "sira_recipient_share",
            },
        ),
        migrations.CreateModel(
            name="GPSPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        db_index=True, geography=True, srid=4326
                    ),
                ),
                ("accuracy_m", models.FloatField()),
                ("speed_kmh", models.FloatField(blank=True, null=True)),
                ("bearing", models.FloatField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                ("is_from_offline_sync", models.BooleanField(default=False)),
                ("is_suspect", models.BooleanField(default=False)),
                ("suspect_reasons", models.JSONField(default=list)),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_points",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point GPS",
                "verbose_name_plural": "Points GPS",
                "db_table": "sira_gps_point",
                "ordering": ["recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(fields=["status"], name="sira_ride_status_bbb7cb_idx"),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(fields=["client"], name="sira_ride_client__e033dc_idx"),
        ),
        migrations.AddIndex(
            model_name="ride",
            index=models.Index(fields=["driver"], name="sira_ride_driver__826389_idx"),
        ),
        migrations.AddIndex(
            model_name="gpspoint",
            index=models.Index(
                fields=["ride", "recorded_at"], name="sira_gps_po_ride_id_11fc32_idx"
            ),
        ),
    ]
