# Generated by Django 5.2.14 on 2026-05-22 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rides", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouvert"),
                            ("INVESTIGATING", "En cours d'investigation"),
                            ("RESOLVED_CLIENT", "Résolu en faveur du client"),
                            ("RESOLVED_DRIVER", "Résolu en faveur du conducteur"),
                            ("DISMISSED", "Rejeté"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "verbose_name": "Litige",
                "verbose_name_plural": "Litiges",
                "db_table": "sira_dispute",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="sira_disput_status_bb93b2_idx"
                    ),
                    models.Index(
                        fields=["ride"], name="sira_disput_ride_id_f6c54b_idx"
                    ),
                ],
            },
        ),
    ]
